language: cpp
before_script:
- sudo apt-get install graphviz
- sudo apt-get install doxygen
script:
- cd Homework5
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen doc/Doxyfile
deploy:
#  - provider: script
#    skip_cleanup: true
#    script:
#    - curl -T editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uSergeyTyurin:$BINTRAY_API_KEY "https://api.bintray.com/content/sergeytyurin/otus-cpp/editor/$TRAVIS_BUILD_NUMBER/editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    target-branch: doc_hw5
    local-dir: doc
    on:
      branch: master
